services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: jashuu
      POSTGRES_PASSWORD: jashuu
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    container_name: user_service_mongodb
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: jashwanth
      MONGO_INITDB_ROOT_PASSWORD: jashwanth
      MONGO_INITDB_DATABASE: user-service
    ports:
      - "27017:27017"
    networks:
      - mongodb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # MongoDB Web Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jashwanth
      ME_CONFIG_MONGODB_ADMINPASSWORD: jashwanth
      ME_CONFIG_MONGODB_URL: mongodb://jashwanth:jashwanth@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - mongodb

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" #RabbitMQ message broker
      - "15672:15672" #RabbitMQ Management UI (http://localhost:15672)
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  mongodb:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb_data:
