spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: jashuu
    password: jashuu
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8084

logging:
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7