spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/User-Service?authSource=admin

#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    virtual-host: ${RABBITMQ_VHOST:guest}
#    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

logging:
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

keycloak:
  admin:
    username: jashwanth
    password: jashwanth
    url: http://localhost:8443
    realm: mj-ecom
    client-id: oauth2-pkce
    client-uid: f77ac29c-3670-4532-8e9c-10e0bdf76172