spring:
  data:
    mongodb:
      uri: mongodb://jashwanth:jashwanth@localhost:27017/user-service?authSource=admin

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

logging:
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7