spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    virtual-host: ${RABBITMQ_VHOST:guest}
#    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

logging:
  file:
    name: logs/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

keycloak:
  admin:
    username: jashwanth
    password: jashwanth
    url: http://keycloak:8080
    realm: mj-ecom
    client-id: oauth2-pkce
    client-uid: 994b19fb-3436-4442-8cc2-837d994c9412