spring:
  application:
    name: user-service

  data:
    mongodb:
      # uri: mongodb://jashwanth:jashwanth@localhost:27017/user-service
      host: localhost
      port: 27017
      database: user-service
      username: jashwanth
      password: jashwanth
      authentication-database: admin

#  datasource:
#    url: jdbc:postgresql://localhost:5432/user
#    username: jashuu
#    password: jashuu

#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#   database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true

#  datasource:
#    url: jdbc:h2:mem:test

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082


